### PR TITLE
Reference map feature 

### PR DESCRIPTION
**Pull request by shortercode**
@jcf120 check this out, seems to work pretty smoothly

### CODE REVIEW

**Comment by jcf120** [comment]
Works a treat!

**Comment by jcf120** [comment]
Might be worth adding a check for repeated refs.

**Comment by shortercode** [comment]
Yeah repeat references was one of the edge cases I hadn't decided on, could
be nice in certain situations to return an array for the reference... But
it would be rather confusing to do this automatically. Better bet would be
to advise using a classname and `search`.

So yeah I'll add in an existence check.

The other thing I was wondering was if we should make the reference object
part of the main parameter object, this could potentially allow the use of
multiple references per create call. What's your thoughts on that?

**Comment by jcf120** [comment]
Yeah, that might be handy. So what, something like?:

``` javascript
Doom.create({
    refMap: containerRefs,
    ref: 'container',
    childNodes: [
        { ref: 'header' },
        {
            refMap: inputRefs,
            child: { ref: 'field1' }
        }
    ]
});
```

**Comment by shortercode** [comment]
Yup exactly, should just be a small change to using a context stack instead of a single reference. I'll start on it in a moment. Thinking about this it actually works quite nicely for MVC applications, as you can have something like

```
class MyView {
  constructor () {
    this.elements = {};
    Doom.create({
      refMap: this.elements,
      ref: "container",
      child: {
        ref: "label",
        innerHTML: "loading"
      }
    });
  }
  setValue (str) {
    this.elements.label.innerHTML = str;
  }
}
```

Which is rather tidy I think!

**Comment by jcf120** [comment]
Yeah, I'm finding lots of places where it neatly swaps in!

**Comment by shortercode** [comment]
Sweet! Should I keep the object map argument as well? So you can do either

```
const objectMap = {};

Doom.create({ref:  "object"}, objectMap);

// or

Doom.create({
  ref: "object",
  refMap: objectMap
});
```

**Comment by jcf120** [comment]
I guess it's nice to have the option. The inconsistency feels slightly messy, but I do like it being concise.

**Comment by shortercode** [comment]
I think I favour the 2nd, just because we take everything else as part of the parameter object.

I'll take out the first, it's a very small change so we can always add it back in. Got the stack working just trying to update the touch test page to use the references then will commit.

**Comment by shortercode** [comment]
Okay I think this is ready!

**Comment by jcf120** [comment]
Works for me :)

**Pull request merged**
