### PR TITLE
Extend 'modify' to accept class arrays.

### PR DESCRIPTION
**Pull request by jcf120**
Allowing less verbose class manipulation:

``` javascript
Doom.modify({
    element: elem,
    addClasses: [
        ‘class1’,
        ‘class2’
    ]
});
```

### CODE REVIEW

**Comment by shortercode** [comment]
I'd actually considered this before but didn't decide on what the interface should be. Some of the alternatives I came up with:
- space delimited string of classes
- addClass can accept string or array

Also bear in mind the classlist api itself supports multiple classes per call for add and remove

HTMLElement.classList.add(String[, String]...)
HTMLElement.classList.remove(String[, String]...)
HTMLElement.classList.toggle(String[, Boolean]) // Second arg can be used to specify only add(true) or only remove(false)

I prefer to follow the pattern set by the API in most situations, what are your thoughts?

**Comment by jcf120** [comment]
Ah, looks like the included classList.js is outdated. You've written in the header that you've added modifications - anything major?

**Comment by jcf120** [comment]
Hmmm, there's not much in it. Space delimiters seem pretty too.

``` javascript
Doom.modify({
    element: elem,
    addClass: 'class1 ' +
              'class2'
});
```

I guess I'm bothered that the arg name is misleading.

**Comment by jcf120** [comment]
I suppose arrays have the added safety of preventing accidental class concatenation. In the above snippet I forgot the space after `'class1'` at first.

**Comment by shortercode** [comment]
Comparing the version online it looks like I stripped the partial support/ repair existing chunk from the polyfill as Doom didn't need the features it was fixing ( multi-arg add/remove and the force option from toggle ). Also I changed the whitespace, as the original lib has a really freaky coding style... I can't see any changes to the lib though, where did you find a new one??

**Comment by shortercode** [comment]
I kinda like the space delimiter option as well, and definitely agree the name is misleading... I think in most situations I would use `addClass: "classA classB"` or  `addClass: "classA" + " " + "classB"`.

Perhaps we should go with the approach of letting the user choose, there's a few alternate use modes lying around already following that thinking. For example style accepts either a string or an object, personally I rarely use the object form but its kinda useful where you have a lot of rules.

I suggest we upgrade addClass to allow for space delimited strings and add a new function called addClasses which accepts an array of one or more strings.

**Comment by jcf120** [comment]
Guess I mistook the stuff you stripped for added features at origin. (I hadn't bothered going through history.)

Alright I'm happy with that. I'll whack in the delimiter splitting.

**Comment by shortercode** [comment]
Cool, I'm going to make some tweaks to the classlist polyfill.

**Comment by jcf120** [comment]
Righto. Gonna add protection against `addClasses:['class1 class2']`?

**Comment by shortercode** [comment]
Yeah I'll see what I can come up with for that.

**Comment by shortercode** [comment]
Turns out we already had protection for spaces in tokens, the index search method will throw if the token contains a space character or has no characters. 

I've fixed up our add and remove methods to accept multiple tokens in a single call, also noticed the polyfill was creating a new classlist instance each time you requested the object which is kinda bad. So have fixed that.

New pattern I came up with was to create a getter on Element.prototype for "classList". When accessed the first time on an Element instance this creates a new instance of classList and attaches a getter to the Element instance for classList ( which has a higher priority than the prototypes getter ). When accessed the new getter updates the existing classList from the className property on the element then returns it.

This isn't flawless; if you request the classList and store it, then modify the className on the element then the classList will go out of sync... but the old one wouldn't have resync'd it ever, it was basically single use. However, I think storing it is a bit of a weird use case.

So overall I think we're closer to spec and little faster!

**Comment by shortercode** [comment]
Also just revised those new methods to use the multi argument form of classList, to reduce our iterator usage. If your happy with those we can merge now I think

**Comment by jcf120** [comment]
Nice. Yeah, I'm happy with that. Merge baby merge.

**Comment by shortercode** [comment]
Niiiiiice all good

**Pull request merged**
