### PR TITLE
Mouse zero fix

### PR DESCRIPTION
**Pull request by jcf120**
Only affects desktop.

### CODE REVIEW

**Comment by shortercode** [comment]
I don't think this works, as it doesn't take into account that on certain devices you can have mouse input as well as touch. It should use a proper existence check like `"pageX" in event ? event.pageX : event.changedTouches[0].pageX`.

**Comment by jcf120** [comment]
Is alright to have it use `pageX/Y` on touch devices that support mouse? Do we know that the values are equivalent? Perhaps it should depend on whether the first event was `touch start` or `mousedown`

**Comment by shortercode** [comment]
The values are equivalent, just the pixel value from the top left of the document. There's the slightly bigger issue that we presume a single pointer at all times, but the way it's worked means that it won't break with multiples, it just acts in a slightly wrong way. 

With 2 touch events, the first touchstart (only the first) would begin the gesture. Each movement would adjust the position to the last active touch input, so jumping between the 2. First touchend (only the first) would end the gesture, the other input would be ignored from that point onwards.

If a user was providing a touch input and a mouse input simultaneously it would act the same way.

So the bigger point is if we consider the gesture system to be broken because of that behaviour?

**Comment by jcf120** [comment]
I can't say it bothers me enough to change it!

**Comment by shortercode** [comment]
yeah that's roughly the reason why I've left it as is for the last... I dunno 2 years? Been awhile since I wrote that. Always kinda bugged me but the multi input implementation is kinda hard. I've had a couple of goes to rough one out but it's such a big change, makes the gesture system much more complicated.

**Comment by jcf120** [comment]
Now using `in event ?:`. Good to merge?

**Comment by shortercode** [comment]
Yarp looks good to me!

**Pull request merged**
