### PR TITLE
Fix operator order

### PR DESCRIPTION
**Pull request by jcf120**
`!` was taking precedence over `in`, so testing the prototype always
failed.

### CODE REVIEW

**Comment by shortercode** [comment]
Nice spot, was there a specific issue with the polyfills or did you just notice them being overridden?

**Comment by jcf120** [comment]
Not hit the issue yet. I tried running the build through flowtype and it flagged it up `boolean in obj` as a type error.

It lists 165 errors in total. Most seem to relate to relate to extending prototypes. Not yet sure why flowtype doesn't like that.

**Comment by shortercode** [comment]
weird, I was looking at flow this morning. decided I couldn't be bothered with it, we use runtime type checking at my office so seems silly to use multiple systems. Mmm my guess is to prevent engine deop's, V8 quite often uses a native class to represent a JS class where it can, but obviously modifying the prototype or modifying the instance of class breaks that model

**Comment by shortercode** [comment]
I've been wanting to do a rewrite of doom for a while, so any suggestions to the syntax guidelines and feature base is appreciated. I'll create an issue for them

**Comment by jcf120** [comment]
What's the runtime checking you use at work?

Feature I've wanted from time to time: a way to build node refs a creation. Maybe something like:

``` javascript
var refs = {};
Doom.create({
    childNodes: [
        /* some complex hierarchy */
        {
            tagName: 'input',
            ref: 'firstName'
        }
    ]
}, refs);

refs.firstName.value = 'Bob';
```

**Comment by shortercode** [comment]
We have a collection of assert style utility functions, like `RequireInstanceOf(myElement, Element)` and `RequireOptionalString(null)` (the optional ones allow the type or null). It's a fairly robust system and doesn't seem to carry too much overheard. Started using it in some of my personal projects, but it means functions take longer to write...

I have actually always wanted something like that as well, it's a major limitation of the `create` method at the moment that you have to go get loads of references after the call. That's a pretty neat solution, it's kinda like using an id except it doesn't become a label on the element.

**Comment by shortercode** [comment]
Created a new issue [here ](https://github.com/shortercode/Doom.js/issues/9) for the feature

**Pull request merged**
